{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "morecomplex.serviceAccountName" . }}
  labels:
{{ include "morecomplex.selectorLabels" . | nindent 4 }}
{{- end -}}
