apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awscluster
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/erkules/clusterapi-aws-template.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: aws1
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
