apiVersion: networking.k8s.io/v1beta1
kind:       Ingress
metadata:
  name: fanout
  annotations:
    traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
spec:
  rules:
  - http:
      paths:
      - path: /www
        backend:
          serviceName:  www
          servicePort:  80
      - path: /web
        backend:
          serviceName:  web
          servicePort:  80

