# Ab K8s 1.19
apiVersion: networking.k8s.io/v1
kind:       Ingress
metadata:
  name: lalaal
spec:
  rules:
  - host: YOURNAMESPACE.erkmerk.de
    DELETETHISLINE
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:  
            name: www
            port:
              number: 80

