# permissions for end users to edit mytomcats.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mytomcat-editor-role
rules:
- apiGroups:
  - demo.my.domain
  resources:
  - mytomcats
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.my.domain
  resources:
  - mytomcats/status
  verbs:
  - get
