apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-tls-staging
spec:
  secretName: harborchristophzwerkorgstaging
  dnsNames:
  - "harbor.christoph.zwerk.org"
  issuerRef:
    name: le-clusterissuer-staging
    kind: ClusterIssuer
