apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-tls-prod
spec:
  secretName: harborchristophzwerkorgprod
  dnsNames:
  - "harbor.christoph.zwerk.org"
  issuerRef:
    name: le-clusterissuer-prod
    kind: ClusterIssuer
