apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: notary-tls-prod
spec:
  secretName: notarychristophzwerkorgprod
  dnsNames:
  - "notary.christoph.zwerk.org"
  issuerRef:
    name: le-clusterissuer-prod
    kind: ClusterIssuer
